site_name: My MkDocs Sandbox
site_url: https://hotenov.github.io/my-sandbox-git-github/

nav:
  - Home: index.md
  - About: about.md

theme:
  name: material
  favicon: img/favicon.ico

plugins:
- search
- autorefs
- mkdocstrings
